<?php include ("head.php"); ?>
<?php include("header.php"); ?>
<?php global $HeaderTitle;  ?> 
<?php $HeaderTitle = "quiénes somos";  ?>
<article class="sobreWrapper historiaSection">
	<?php include("innerHeaderBackground.php"); ?>
	<section class="wrapper">
		<h1 class="mainClaim">historia</h1>
		<p>El inicio de QDQ media se remonta al año 1997 cuando, Un grupo de profesionales procedentes del Grupo Telefónica y del sector financiero, se unieron para crear un grupo editorial que pudiera posicionarse fuertemente en entornos multimedia, obteniendo sus ingresos de la publicidad y del comercio electrónico, naciendo así el Grupo Índice Multimedia, un conglomerado con capital 100% español.</p>
		<p>En el seno de este grupo nace QDQ, siglas de “Qué, Dónde y Quién”, un editor de guías telefónicas. Editándose al año siguiente, en 1998, la primera con el nombre de “QDQ, la guía útil”, siendo su primer ejemplar el del Corredor de Henares. El soporte publicitario en formato papel llegará a alcanzar una tirada de más de 15 millones de ejemplares repartidos por toda España y con más de 60 guías diferentes, según las distintas Comunidades.</p>
		<p>La guía QDQ actuaba como soporte de servicio local para empresas y de contacto y publicidad para pymes y los esfuerzos se enfocaron en conseguir que se posicionara rápidamente en el mercado desarrollando una fuerza de ventas en todo el territorio nacional y una fuerte relación con sus clientes fundamentando su base en el triángulo: Servicio, Precio y Calidad.</p>
		<figure class="leftSide"><img src="img/qdqRevista.png"><figcaption>Distintos ejemplares y versiones de la antigua guía QDQ.</figcaption></figure>
		<p>Años más tarde, en 2001, la empresa Wanadoo -líder europea en edición de guías impresas y online, creación de portales y servicio de acceso a Internet-, filial de France Telecom, compra parte del Grupo Índice Multimedia, quedando fuera 20 minutos al adquirir sólo los directorios. France Telecom era un conglomerado formado, en aquel momento, por Orange, Wanadoo, Equant y Pages Jaunes. Ese mismo año QDQ lanza un servicio de páginas blancas con particulares, además de ser el primero en sacar una suerte de “Callejero fotográfico” para algunas ciudades de España como Madrid, Barcelona, Valencia, Santander y Zaragoza.</p>
		<p>Poco tiempo después el Grupo Índice Multimedia pasa a llamarse QDQ media y se inaugura el buscador QDQ.com, versión online de “QDQ, la guía útil”, y que cuenta con una base de datos de más de 2 millones de empresas.</p>
		<p>En marzo de 2004, QDQ media pasa a ser filial de Pages Jaunes, que aglutina toda la actividad relacionada con guías: “Les Pages Jaunes, Marketing Services, Petites Annonces, Horyzon y QDQ media”, a la vez que la misma Pages Jaunes pasa a depender del grupo KKR.</p>
		<p>En estos años QDQ media se consolida como la segunda empresa española en su sector, y en 2006 tras el éxito del buscador QDQ.com, refuerza su posición de liderazgo en materia de innovación y desarrollo de servicios y contenidos para los usuarios añadiendo nuevas ciudades a sus Callejeros fotográficos y creando un concepto innovar hasta aquel momento: el de la búsqueda de ciudades en 3D, además también incorporaron información meteorológica y de tráfico, siendo posible consultar todos estos servicios en todas las lenguas oficiales de España, así como en francés, inglés y portugués. Ese mismo año, QDQ recibe el Premio a la mejor guía europea por la EADP.</p>
		<p>Tras la firma en 2007 de un acuerdo con ebay que dura todo un año, en 2008 se firma el acuerdo entre Google™ y QDQ media convirtiéndose esta última en el 1º reseller de Google™ en España hasta llegar, a día de hoy, a ser el mayor en toda la Península Ibérica, englobando a España y Portugal.</p>
		<p>Al año siguiente, en 2009, se inicia el cambio que marcará el nuevo rumbo de la compañía al variar su modelo de negocio, pasando de soporte de papel a agencia digital, aunque ya llevaban desde 2002 estando presentes en internet con su buscador.</p>
		<figure><img src="img/interiorQDQ.png"><figcaption>Trabajadores en la sede de QDQmedia en Madrid</figcaption></figure>
		<p>En marzo de 2010, Pages Jaunes Group hace pública la adquisición de 123people, uno de los líderes mundiales en internet en búsqueda de información de personas y su integración con QDQ media supone una consolidación de su expansión en internet al permitirle diferenciarse de sus competidores.</p>
		<p>En 2011 QDQ media se convierte en un grupo puntero al adquirir las agencias Optimizaclick y Trazada, cubriendo así todo el espectro de clientes posible en el mercado al especializarse, cada una de ellas, en un sector específico, además de que ese mismo año se inicia el acuerdo con 11870.com.</p>
		<p>La transición a digital finaliza a principios de 2013 ya que la última tirada de la guía en formato papel es lanzada en Diciembre de 2012, a partir de ese momento QDQ media se convierte en la mayor agencia de marketing online del país integrando un servicio que va desde la pequeña y mediana empresa hasta las grandes compañías. Al mismo tiempo el Grupo Pages Jaunes cambia de nombre y pasa a formar parte del grupo Solocal pasando a pertenecer a este gran conglomerado de empresas del sector.</p>
		<p>Nosotros hemos evolucionado a la par que lo hacía internet y prueba de ello es el cambio de nuestro portal QDQ.com, nuestro buscador de negocios online, y del que puedes <a href="">repasar su evolución</a> desde que comenzó en 2001 hasta nuestros días.</p>
		<p>También puedes consultar la historia de QDQ media en <a href="https://es.wikipedia.org/wiki/Qdq_media">Wikipedia</a>.</p>
	</section>
</article><!-- fin sobreWrapper -->
<?php include("footer.php"); ?>
</body>
</html>